export const GET_USERS_ACTION_STARTED = '@GET_USERS_ACTION_STARTED';
export const GET_USERS_ACTION_SUCCESS = '@GET_USERS_ACTION_SUCCESS';
export const GET_USERS_ACTION_FAILED = '@GET_USERS_ACTION_FAILED';

export const GET_USER_POSTS_ACTION_STARTED = '@GET_USER_POSTS_ACTION_STARTED';
export const GET_USER_POSTS_ACTION_SUCCESS = '@GET_USER_POSTS_ACTION_SUCCESS';
export const GET_USER_POSTS_ACTION_FAILED = '@GET_USER_POSTS_ACTION_FAILED';

export const SEARCH_ACTION_STARTED = '@SEARCH_ACTION_STARTED';
export const SEARCH_POSTS_ACTION_SUCCESS = '@SEARCH_POSTS_ACTION_SUCCESS';
export const LOAD_MORE_SEARCH_POSTS_ACTION_SUCCESS = '@LOAD_MORE_SEARCH_POSTS_ACTION_SUCCESS';
export const SEARCH_USERS_ACTION_SUCCESS = '@SEARCH_USERS_ACTION_SUCCESS';
export const SEARCH_ACTION_FAILED = '@SEARCH_ACTION_FAILED';

export const CLEAR_SEARCH_DATA = '@CLEAR_SEARCH_DATA';

export const CHANGE_LANGUAGE = '@CHANGE_LANGUAGE';
