export const FETCH_CATEGORIES_ACTION_STARTED = 'FETCH_CATEGORIES_ACTION_STARTED';
export const FETCH_CATEGORIES_ACTION_SUCCESS = 'FETCH_CATEGORIES_ACTION_SUCCESS';
export const FETCH_CATEGORIES_ACTION_FAILED = 'FETCH_CATEGORIES_ACTION_FAILED';

export const ADD_CATEGORY_ACTION_STARTED = 'ADD_CATEGORY_ACTION_STARTED';
export const ADD_CATEGORY_ACTION_SUCCESS = 'ADD_CATEGORY_ACTION_SUCCESS';
export const ADD_CATEGORY_ACTION_FAILED = 'ADD_CATEGORY_ACTION_FAILED';

export const SET_SELECTED_CATEGORIES = 'SET_SELECTED_CATEGORIES';
