export const FETCH_POSTS_ACTION_STARTED = '@FETCH_POSTS_ACTION_STARTED';
export const FETCH_POSTS_ACTION_SUCCESS = '@FETCH_POSTS_ACTION_SUCCESS';
export const FETCH_POSTS_ACTION_FAILED = '@FETCH_POSTS_ACTION_FAILED';
