export const FETCH_POSTS_ACTION_STARTED = '@FETCH_POSTS_ACTION_STARTED';
export const FETCH_POSTS_ACTION_SUCCESS = '@FETCH_POSTS_ACTION_SUCCESS';
export const REFRESH_POSTS_ACTION_SUCCESS = '@REFRESH_POSTS_ACTION_SUCCESS';
export const FETCH_POSTS_ACTION_FAILED = '@FETCH_POSTS_ACTION_FAILED';

export const SEARCH_POSTS_ACTION_STARTED = '@SEARCH_POSTS_ACTION_STARTED';
export const SEARCH_POSTS_ACTION_SUCCESS = '@SEARCH_POSTS_ACTION_SUCCESS';
export const SEARCH_POSTS_ACTION_FAILED = '@SEARCH_POSTS_ACTION_FAILED';

export const ADD_POST_ACTION_STARTED = '@ADD_POST_ACTION_STARTED';
export const ADD_POST_ACTION_SUCCESS = '@ADD_POST_ACTION_SUCCESS';
export const ADD_POST_ACTION_FAILED = '@ADD_POST_ACTION_FAILED';

export const FETCH_POST_ACTION_STARTED = '@FETCH_POST_ACTION_STARTED';
export const FETCH_POST_ACTION_SUCCESS = '@FETCH_POST_ACTION_SUCCESS';
export const FETCH_POST_ACTION_FAILED = '@FETCH_POST_ACTION_FAILED';

export const ADD_POST_COMMENT_ACTION_STARTED = '@ADD_POST_COMMENT_ACTION_STARTED';
export const ADD_POST_COMMENT_ACTION_SUCCESS = '@ADD_POST_COMMENT_ACTION_SUCCESS';
export const ADD_POST_COMMENT_ACTION_FAILED = '@ADD_POST_COMMENT_ACTION_FAILED';
