export const USER_INFO_ACTION_STARTED = '@USER_INFO_ACTION_STARTED';
export const USER_INFO_ACTION_SUCCESS = '@USER_INFO_ACTION_SUCCESS';
export const USER_INFO_ACTION_FAILED = '@USER_INFO_ACTION_FAILED';

export const FETCH_USER_POSTS_ACTION_STARTED = '@FETCH_USER_POSTS_ACTION_STARTED';
export const FETCH_USER_POSTS_ACTION_SUCCESS = '@FETCH_USER_POSTS_ACTION_SUCCESS';
export const FETCH_USER_POSTS_ACTION_FAILED = '@FETCH_USER_POSTS_ACTION_FAILED';
export const REFRESH_USER_POSTS_ACTION_SUCCESS = '@REFRESH_USER_POSTS_ACTION_SUCCESS';

export const UPDATE_USER_INFO_ACTION_STARTED = '@UPDATE_USER_INFO_ACTION_STARTED';
export const UPDATE_USER_INFO_ACTION_SUCCESS = '@UPDATE_USER_INFO_ACTION_SUCCESS';
export const UPDATE_USER_INFO_ACTION_FAILED = '@UPDATE_USER_INFO_ACTION_FAILED';

export const LOGOUT = '@LOGOUT';
